name: Update flake.lock

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * FRI"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Update flake.lock
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          nix flake update --commit-lock-file

      - name: Flake check
        run: nix flake check --all-systems

      - name: Build default output
        run: nix build

      - name: Push
        run: |
          if git log -1 --pretty=%B | grep -q "flake.lock"; then
            git push origin main
          else
            echo "No changes to flake.lock"
          fi
